menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/leonfancy

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-106539432-1

# Copyright Infomation
startyear: 2017
